### ISSUE TITLE
Custom Supervision.Decider doesn't catch exception produced by GenericBulkPullerAsync

### ISSUE THREAD

**Issue by cppexpert** [MfgLabs/akka-stream-extensions#16]
I realize it's not bug of your library per se (probably). But maybe you guys know why custom Supervision.Decider doesn't catch exception produced by GenericBulkPullerAsync ?

Details are here: http://stackoverflow.com/questions/32290285/custom-supervision-decider-doesnt-catch-exception-produced-by-actorpublisher

**Comment by Timshel** [comment]
Cf : https://github.com/akka/akka/issues/18359
