### ISSUE TITLE
Deprecate SinkExt.collect

### ISSUE THREAD

**Issue by joearasin** [MfgLabs/akka-stream-extensions#18]
As far as I can tell, there's no difference between Akka's `Sink.seq` and this library's `SinkExt.collect`. It probably makes sense to deprecate the latter.

It's also worth examining whether the unfolding source methods make sense w/r/t the existence of `Source.unfold` and `Source.unfoldAsync`

**Comment by Timshel** [comment]
Yes just released the `0.11` and removed the already deprecated `Source.unfold` and added deprecated to `Source.unfoldAsync`.
