### ISSUE TITLE
0.10.0 is not published on Bintray

### ISSUE THREAD

**Issue by tlockney** [MfgLabs/akka-stream-extensions#20]
The readme mentions version 0.10.0, but this does not appear to be published on bintray.

**Comment by malcolmgreaves** [comment]
I am currently using this library. At the moment, not having `0.10.0` published is a huge blocker on my team. Respectfully -- when will `0.10.0` be published? If we don't have this version soon, we're strongly considering moving away from `commons-aws` and `akka-stream-extensions` to depend on our own forks.

**Comment by malcolmgreaves** [comment]
@tlockney made a note of this on `commons-aws` here: https://github.com/MfgLabs/commons-aws/issues/19

**Comment by malcolmgreaves** [comment]
@atamborrino and @dmnpignaud -- this one is related to the PR I made on commons-aws https://github.com/MfgLabs/commons-aws/pull/20. We'd have to publish version `0.10.0` here for that PR to work (I did it locally during dev and testing for the PR).

**Comment by Timshel** [comment]
I just published the 0.10.0. Sorry for the delay.

**Comment by malcolmgreaves** [comment]
thank you @Timshel !
