### ISSUE TITLE
Contribution to akka-stream-contrib

### ISSUE THREAD

**Issue by juanjovazquez** [MfgLabs/akka-stream-extensions#21]
Lightbend has recently promoted a [repository](https://github.com/akka/akka-stream-contrib) for akka-streams contributions.  Some of your extensions seem particularly suitable for ending up in this project. I personally use some of the extensions in this project and so far I'm happy with them. However, some work needs to be done in order to update them to the recent Akka 2.4.4 version, and posibly to deprecate some artifacts as the standard library has been improved lately. 

So, please, do you have any plans to contribute to this new contrib repo?. If not, do you have any objections to let me contribute adapting the code conveniently?.

Thanks in advance and keep up the good work.

**Comment by atamborrino** [comment]
Hey @juanjovazquez 

You can of course take some ideas that we've implemented in this repo and push them to akka-streams contributions. No copyrights ;)

**Comment by juanjovazquez** [comment]
@atamborrino Thanks. I'll do that!
