### ISSUE TITLE
Q: How to use PostgreSQL sink from Java akka? 

### ISSUE THREAD

**Issue by nikos** [MfgLabs/akka-stream-extensions#22]
Any hint would be fantastic to see how PgStream#insertStreamToTable can be used as sink from a Java perspective?
Thanks, Niko

**Comment by Timshel** [comment]
Almost one year late, but `insertStreamToTable` is a `Flow` so you would need to combine it (`to`) with a sink (Ex: `Sink.ignore`) to obtain a `Sink`.
